# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "feature/v4-dev" ]
  pull_request:
    branches: [ "v4" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -race -count=1 -v ./...
